<link href="{{ asset('css/app.css') }}" rel="stylesheet">
<link href="{{ asset('web/css/lineicons.css') }}" rel="stylesheet">
<link href="{{ asset('materialdesignicon/css/materialdesignicons.min.css') }}" rel="stylesheet">
<link href="{{ asset('fontawesome/css/all.min.css') }}" rel="stylesheet">
<link href="{{ asset('web/css/main.css') }}" rel="stylesheet">
<link href="{{ asset('web/css/footer.css') }}" rel="stylesheet">
<link href="{{ asset('datepicker/css/bootstrap-datepicker.min.css') }}" rel="stylesheet">
<link href="{{ asset('web/css/custome.css') }}" rel="stylesheet">
<link href="{{ asset('web/css/hovercss/hover-min.css') }}" rel="stylesheet">
<link href="{{ asset('jqueryui/jquery-ui.min.css') }}" rel="stylesheet">
